apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
  namespace: sos-golpes
  labels:
    app: reports
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - name: reports
          image: sos-golpes-reports:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
          envFrom:
            - secretRef:
                name: app-secret
