apiVersion: v1
kind: Service
metadata:
  name: reports-service
  namespace: sos-golpes
  labels:
    app: reports
spec:
  type: ClusterIP
  selector:
    app: reports
  ports:
    - name: http
      port: 8000
      targetPort: 8000
