events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 8080;

        location /api/auth/ {
            set $identity_upstream http://identity-service:8000;

            proxy_pass $identity_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/threats/ {
            set $threat_upstream http://threat-service:8000;

            proxy_pass $threat_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/admin/ {
            set $admin_upstream http://admin-service:8000;

            proxy_pass $admin_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/audit/ {
            set $audit_upstream http://audit-service:8000;

            proxy_pass $audit_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/user/ {
            set $user_upstream http://user-service:8000;

            proxy_pass $user_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            set $frontend_upstream http://frontend:80;

            proxy_pass $frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}