services:
  frontend:
    build: ./frontend
    container_name: sos_golpes_frontend
    ports:
      - "3000"
    env_file:
      - .env

  api-gateway:
    build: ./api-gateway
    container_name: sos_golpes_gateway
    ports:
      - "8080:8080"
      - "443:8443"
    env_file:
      - .env

  identity-service:
    build: ./services/identity
    container_name: sos_golpes_identity
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  user-service:
    build: ./services/user
    container_name: sos_golpes_user
    env_file:
      - .env
    volumes:
      - keys_data:/var/keys
    depends_on:
      db:
        condition: service_healthy
    
  threat-service:
    build: ./services/threat
    container_name: sos_golpes_threat
    env_file:
      - .env
    volumes:
      - keys_data:/var/keys
    depends_on:
      db:
        condition: service_healthy
  
  admin-service:
    build: ./services/admin
    container_name: sos_golpes_admin
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  audit-service:
    build: ./services/audit
    container_name: sos_golpes_audit
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: sos_golpes_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  keys_data:
