services:
  web:
    build:
    container_name: sos_golpes_web
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/html/app
      - ./db:/var/www/html/database
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: sos_golpes_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
