apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: sos-golpes
  labels:
    app: audit
spec:
  type: ClusterIP
  selector:
    app: audit
  ports:
    - name: http
      port: 8000
      targetPort: 8000
