apiVersion: v1
kind: Service
metadata:
  name: threat-service
  namespace: sos-golpes
  labels:
    app: threat
spec:
  type: ClusterIP
  selector:
    app: threat
  ports:
    - name: http
      port: 8000
      targetPort: 8000
