apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: sos-golpes
  labels:
    app: admin
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - name: http
      port: 8000
      targetPort: 8000
