apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: sos-golpes
  labels:
    app: identity
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - name: http
      port: 8000
      targetPort: 8000
