name: "CI/CD Pipeline"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Bandit:
    name: Bandit Scan (SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instalação do Bandit
        run: pip install bandit
    
      - name: Executar Bandit
        run: bandit -r . -ll -x ./venv

  SnykSAST:
    name: Snyk Scan (SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk Code Scan (SAST)
        run: snyk code test --org=${{ secrets.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  SnykSCA:
    name: Snyk Scan (SCA)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Snyk CLI
        uses: snyk/actions/setup@master
      
      - name: Instalar dependências do Microserviço
        run: |
          pip install -r services/${{ matrix.service }}/requirements.txt
      
      - name: Snyk SCA
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --file=services/${{ matrix.service }}/requirements.txt \
                    --package-manager=pip \
                    --org=${{ secrets.SNYK_ORG }}

  SemgrepSAST:
    name: Semgrep Scan (SAST)
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v6
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  build:
    name: Build
    needs: [Bandit, SnykSAST, SnykSCA, SemgrepSAST]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build da imagem (${{ matrix.service }})
        run: docker build -t sos-golpes-${{ matrix.service }}:latest ./services/${{ matrix.service }}

      - name: Salvar imagem como artefato
        run: docker save sos-golpes-${{ matrix.service }}:latest -o sos-golpes-${{ matrix.service }}.tar

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ matrix.service }}
          path: sos-golpes-${{ matrix.service}}.tar

  ZapDAST:
    name: OWASP ZAP (DAST)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ matrix.service }}

      - name: Carregar imagem
        run: docker load -i sos-golpes-${{ matrix.service }}.tar

      - name: Subir aplicação
        run: |
          docker run -d -p 8000:8000 --network=host \
            --name sos-golpes-${{ matrix.service }} sos-golpes-${{ matrix.service }}:latest
          sleep 15

      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.8.0
        with:
          target: "http://localhost:8000/openapi.json"
          format: "openapi"
          allow_issue_writing: false
          artifact_name: 'zap_scan$_{{ matrix.service }}'

  push:
    name: Push to Docker Hub
    needs: ZapDAST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]

    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Carregar imagem
        run: docker load -i sos-golpes-${{ matrix.service }}.tar

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag e push para o Docker Hub
        run: |
          docker tag sos-golpes-${{ matrix.service }}:latest ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:latest

      - name: Deslogar do Docker Hub
        run: docker logout