name: "CI/CD Pipeline"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Bandit:
    name: Bandit Scan (SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instalação do Bandit
        run: pip install bandit
    
      - name: Executar Bandit
        run: bandit -r . -ll -x ./venv

  SnykSAST:
    name: Snyk Scan (SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk Code Scan (SAST)
        run: snyk code test --org=${{ secrets.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  SnykSCA-matrix:
    name: Snyk Scan (SCA) Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Snyk CLI
        uses: snyk/actions/setup@master
      
      - name: Instalar dependências do Microserviço
        run: |
          pip install -r services/${{ matrix.service }}/requirements.txt
      
      - name: Snyk SCA
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --file=services/${{ matrix.service }}/requirements.txt \
                    --package-manager=pip \
                    --org=${{ secrets.SNYK_ORG }}

  SnykSCA:
    name: Snyk Scan (SCA)
    needs: SnykSCA-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "Todos os services passaram com sucesso (Snyk SCA)"

  SemgrepSAST:
    name: Semgrep Scan (SAST)
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v6
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  build-matrix:
    name: Build Matrix
    needs: [Bandit, SnykSAST, SnykSCA, SemgrepSAST]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push da imagem (${{ matrix.service }})
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:${{ github.sha }} ./services/${{ matrix.service }}
          docker push ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:${{ github.sha }}
      
      - name: Deslogar do Docker Hub
        run: docker logout
  
  build:
    name: Build
    needs: build-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "Todos os builds temporários foram enviados ao Docker Hub"

  ZapDAST-matrix:
    name: OWASP ZAP (DAST) Matrix
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Subir aplicação a partir do Docker Hub
        run: |
          docker run -d -p 8000:8000 --network=host \
            --name sos-golpes-${{ matrix.service }} \
            ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:${{ github.sha }}
          sleep 15

      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.10.0
        with:
          target: "http://localhost:8000/openapi.json"
          format: "openapi"
          allow_issue_writing: false
    
  ZapDAST:
    name: OWASP ZAP (DAST)
    needs: ZapDAST-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "Todos os services passaram com sucesso (OWASP ZAP)"

  push-matrix:
    name: Push Matrix
    needs: ZapDAST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, audit, identity, threat, user]
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag e push de Homologação/Produção
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sos-golpes-${{ matrix.service }}:latest

      - name: Deslogar do Docker Hub
        run: docker logout
  
  push:
    name: Push to Docker Hub
    needs: push-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "Todos os pushs para o Docker Hub da matriz passaram com sucesso"