apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sos-golpes
  labels:
    app: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30443
