apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sos-golpes
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      port: 8000
      targetPort: 8000
